### ISSUE TITLE
Wrong time range on Ping timeout / watch mode

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#12]
```
| Time              | IP              | Port  | Protocol | Connect | Ping    | Local Interface |
| 17:30:26          | 209.194.199.51  | 21    | ftp      | Timeout | 119 ms  | 10.0.68.83      |
| 17:30:33-17:30:27 | 209.194.199.51  | 21    | ftp      | Timeout | NOK     | 10.0.68.83      |
| 17:30:34-17:32:06 | 209.194.199.51  | 21    | ftp      | Timeout | 120 ms  | 10.0.68.83      |
```
Notice that there is negative time range for the NOK ping: 17:30:33-17:30:27 
In fact, there was highly likely only 1 ping timing out.

* In case there is only 1 result for a line, there shouldn't be a time range, but just 1 timestamp
* No range can ever be negative if the source of both timestamps is defined as the start time of the measuring

Another observation:
IF the 'state' changes (new line), the first one drawn will have a range, the second just 1 time, then a range again.

**Comment by kees2125** [comment]
I could not mange to reproduce this issue but I am pretty sure I found what could have caused it and it should be fixed.
