### ISSUE TITLE
Support URL on command line

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#3]
Support:
http://test.com/bla (converts to test.com 80 )
http://test.com:8080/bla (converts to test.com 8080 )
https://test.com/bla (converts to test.com 443 )
ftp://test.bla (test.bla 21)
etc etc
A good start would be to support whatever the Uri class will do (http(s), ftp), and kindly inform the user of non-supported uris if Uri.Port is negative.

**Comment by kees2125** [comment]
The latest develop build supports this.
