### ISSUE TITLE
Support watch mode

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#4]
When starting with -watch , repeat the test until CTRL-C. 

Ideally, outputs a new line every time the result changes only (if output is not redirected):

20:11:11Z - 20:19:08Z  www.test.com 443   [OK]
20:19:11Z - 21:11:01Z  www.test.com 443   [NOK]
21:11:03Z -                  www.test.com 443   [OK]

**Comment by kees2125** [comment]
A watch mode has been added with -w or --watch to activate.
