### ISSUE TITLE
Support name instead of number for well-known protocols

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#5]
www.server.local SMB  converts to www.server.local 445
www.server.local HTTP converts to www.server.local 80
www.server.local RDP converts to www.server.local 3389
www.server.local SQL converts to www.server.local 1433
and so forth:
SSH 22

TODO: expand with more, more, more useful ports

**Comment by kees2125** [comment]
The space separated format is no longer supported but www.server.local:SMB works.
