### ISSUE TITLE
Output error details

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#6]
[NOK] is fine, but adding details is better:
 [NOK]   [DNS timeout]
 [NOK]   [No DNS]
 [NOK]   [Timeout]
 [NOK]   [Refused]
 [OK]   [          ]

Maybe output in Table form:

|| Time || Host || IP || Port || Proto || Result || Details ||
| 20:20:01Z | test.local | 192.168.0.1 | 80 | HTTP | NOK | Refused |

**Comment by kees2125** [comment]
This is the new data format used in the develop version.
