### ISSUE TITLE
In case of connection errors, tell the user the used gateway

### ISSUE THREAD

**Issue by boekabart** [boekabart/QuickConnect#7]
If you can't connect (AND the IP is not on a current subnet), it sometimes helps the user to know what the gateway in use is. In complexer scenarios (including VPNs), there can be non-trivial routing table/rules in place.

.NET can do this type of query:
https://stackoverflow.com/questions/15625023/ip-routing-table-lookup-in-net

**Comment by kees2125** [comment]
The default gateway is now always shown in the output.
